import type { Trip, UserProfile } from './types'

export const demoProfile: UserProfile = {
  id: 'user_fran',
  name: 'Francisco Salazar',
  email: 'fran@example.com',
  avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=160&q=80',
}

export const seedTrips: Trip[] = [
  {
    id: 'trip_japon_2027',
    title: 'Japon entre templos y neones',
    status: 'planned',
    isPublic: false,
    destinations: ['Tokio', 'Kioto', 'Osaka'],
    startDate: '2027-04-05',
    endDate: '2027-04-19',
    coverImageUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    companions: ['Laura', 'Mario'],
    budgetAmount: 6200,
    baseCurrency: 'EUR',
    tags: ['ciudad', 'cultura', 'gastronomia'],
    notes: 'Primer borrador con foco en barrios, trenes y una noche de ryokan.',
    ownerId: 'user_fran',
    createdAt: '2026-06-18T10:00:00.000Z',
    updatedAt: '2026-06-18T10:00:00.000Z',
    members: [
      {
        id: 'member_fran_japon',
        tripId: 'trip_japon_2027',
        userId: 'user_fran',
        name: 'Francisco Salazar',
        email: 'fran@example.com',
        role: 'owner',
      },
      {
        id: 'member_laura_japon',
        tripId: 'trip_japon_2027',
        userId: 'user_laura',
        name: 'Laura',
        email: 'laura@example.com',
        role: 'editor',
      },
    ],
    invitations: [],
    flights: [
      {
        id: 'flight_mad_hnd',
        tripId: 'trip_japon_2027',
        legType: 'ida',
        isInternational: true,
        company: 'Iberia / JAL',
        flightNumber: 'IB281',
        originAirport: 'MAD',
        destinationAirport: 'HND',
        departureAt: '2027-04-05T11:40',
        arrivalAt: '2027-04-06T08:55',
        terminal: 'T4S',
        seat: '24A',
        bookingReference: 'JP7MAD',
        cost: { amount: 870, currency: 'EUR', conversionRate: 1 },
        baggage: {
          cabin: true,
          checked: true,
          weightKg: 23,
          cost: { amount: 0, currency: 'EUR', conversionRate: 1 },
        },
        priorityBoarding: false,
        extras: ['seleccion asiento'],
        notes: 'Comprobar cambio de terminal en Haneda.',
      },
    ],
    vehicleRentals: [],
    accommodations: [
      {
        id: 'acc_tokio',
        tripId: 'trip_japon_2027',
        type: 'hotel',
        name: 'Nohga Hotel Ueno Tokyo',
        address: '2 Chome-21-10 Higashiueno, Taito City, Tokyo',
        bookingReference: 'NOHGA-APR27',
        boardBasis: 'Solo alojamiento',
        checkInAt: '2027-04-06T15:00',
        checkOutAt: '2027-04-11T11:00',
        cost: { amount: 980, currency: 'EUR', conversionRate: 1 },
        touristTax: { amount: 1000, currency: 'JPY', conversionRate: 0.006 },
        deposit: { amount: 0, currency: 'EUR', conversionRate: 1 },
        contactName: 'Recepcion',
        contactPhone: '+81 3-5816-0211',
        services: 'Lavanderia, desayuno opcional, consigna.',
        hotelActivities: 'Catas de sake algunos jueves.',
        guests: '3 adultos',
        room: 'Habitacion triple',
        cancellationPolicy: 'Cancelacion gratis hasta 7 dias antes.',
        notes: 'Buena base para Ueno y Asakusa.',
      },
    ],
    itineraryDays: [
      { id: 'day_tokio_1', tripId: 'trip_japon_2027', date: '2027-04-06', title: 'Llegada a Tokio', notes: 'Dia suave.' },
      { id: 'day_tokio_2', tripId: 'trip_japon_2027', date: '2027-04-07', title: 'Asakusa y Akihabara', notes: 'Activar Suica.' },
    ],
    itineraryItems: [
      {
        id: 'item_sensoji',
        tripId: 'trip_japon_2027',
        dayId: 'day_tokio_2',
        title: 'Templo Senso-ji',
        description: 'Paseo temprano por Nakamise-dori y visita al templo antes de que se llene.',
        imageUrl: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=900&q=80',
        cost: { amount: 0, currency: 'JPY', conversionRate: 0.006 },
        latitude: 35.7148,
        longitude: 139.7967,
        recommendations: {
          food: 'Probar melon pan en Asakusa Kagetsudo.',
          transport: 'Ginza Line hasta Asakusa.',
          tips: 'Ir antes de las 9:00.',
          safety: 'Zona muy concurrida, cuidado con carteras.',
        },
        visited: false,
        order: 1,
      },
      {
        id: 'item_akihabara',
        tripId: 'trip_japon_2027',
        dayId: 'day_tokio_2',
        title: 'Akihabara',
        description: 'Tiendas retro, electronica y paseo nocturno por Chuo-dori.',
        imageUrl: 'https://images.unsplash.com/photo-1513407030348-c983a97b98d8?auto=format&fit=crop&w=900&q=80',
        cost: { amount: 8000, currency: 'JPY', conversionRate: 0.006 },
        latitude: 35.6984,
        longitude: 139.773,
        recommendations: {
          food: 'Ramen cerca de Suehirocho.',
          transport: 'JR Yamanote hasta Akihabara.',
          tips: 'Reservar tiempo para Super Potato.',
        },
        visited: false,
        order: 2,
      },
    ],
    activities: [
      {
        id: 'activity_teamlab',
        tripId: 'trip_japon_2027',
        dayId: 'day_tokio_1',
        name: 'teamLab Planets',
        provider: 'teamLab',
        startsAt: '2027-04-06T18:00',
        location: 'Toyosu',
        cost: { amount: 3800, currency: 'JPY', conversionRate: 0.006 },
        bookingReference: 'TLP-APR06',
        paymentStatus: 'reservado',
        notes: 'Llevar pantalon comodo.',
      },
    ],
    restaurants: [
      {
        id: 'restaurant_narukiyo',
        tripId: 'trip_japon_2027',
        dayId: 'day_tokio_2',
        name: 'Narukiyo',
        cuisine: 'Izakaya',
        location: 'Shibuya, Tokio',
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=35.6585,139.7013',
        averagePrice: { amount: 6500, currency: 'JPY', conversionRate: 0.006 },
        hasReservation: true,
        reservationAt: '2027-04-07T20:30',
        bookingReference: 'Reserva a nombre de Francisco',
        notes: 'Pedir mesa en barra si esta disponible.',
      },
    ],
    contacts: [
      {
        id: 'contact_embassy_jp',
        tripId: 'trip_japon_2027',
        category: 'embajada',
        name: 'Embajada de Espana en Japon',
        phone: '+81 3-3583-8531',
        email: 'emb.tokio@maec.es',
        address: '1-3-29 Roppongi, Minato-ku, Tokyo',
        notes: 'Guardar tambien en el movil.',
      },
    ],
    insurances: [
      {
        id: 'insurance_iati',
        tripId: 'trip_japon_2027',
        provider: 'IATI',
        policyNumber: 'IATI-JP-2027',
        contactPhone: '+34 93 485 77 35',
        contactEmail: 'asistencia@example.com',
        cost: { amount: 148, currency: 'EUR', conversionRate: 1 },
        coverageSummary: 'Asistencia medica, equipaje y cancelacion basica.',
        documentUrl: 'https://example.com/poliza-japon.pdf',
        notes: 'Revisar limites de deportes.',
      },
    ],
    documents: [
      {
        id: 'doc_flight_japan',
        tripId: 'trip_japon_2027',
        category: 'billete',
        title: 'Billetes Madrid - Tokio',
        fileUrl: 'https://example.com/billetes-japon.pdf',
        relatedTo: 'Vuelo IB281',
        notes: 'Pendiente subir PDF real a Supabase Storage.',
      },
    ],
    journalEntries: [
      {
        id: 'journal_intro_japan',
        tripId: 'trip_japon_2027',
        date: '2027-04-05',
        title: 'Antes de despegar',
        body: 'Checklist de reservas completo. Queda cerrar restaurantes en Kioto.',
        photoUrls: ['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80'],
        mood: 'Expectante',
      },
    ],
    expenses: [
      {
        id: 'expense_pocket_wifi',
        tripId: 'trip_japon_2027',
        category: 'Conectividad',
        description: 'eSIM datos ilimitados 15 dias',
        date: '2027-04-05',
        cost: { amount: 34, currency: 'EUR', conversionRate: 1 },
        paid: true,
      },
    ],
  },
  {
    id: 'trip_lisboa_2026',
    title: 'Escapada a Lisboa',
    status: 'completed',
    isPublic: false,
    destinations: ['Lisboa', 'Sintra'],
    startDate: '2026-05-01',
    endDate: '2026-05-05',
    coverImageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1200&q=80',
    companions: ['Ana'],
    budgetAmount: 1100,
    baseCurrency: 'EUR',
    tags: ['escapada', 'ciudad', 'gastronomia'],
    notes: 'Viaje finalizado con notas para repetir Sintra con mas calma.',
    ownerId: 'user_fran',
    createdAt: '2026-04-10T09:00:00.000Z',
    updatedAt: '2026-05-05T22:30:00.000Z',
    members: [
      {
        id: 'member_fran_lisboa',
        tripId: 'trip_lisboa_2026',
        userId: 'user_fran',
        name: 'Francisco Salazar',
        email: 'fran@example.com',
        role: 'owner',
      },
    ],
    invitations: [],
    flights: [],
    vehicleRentals: [
      {
        id: 'car_lisboa',
        tripId: 'trip_lisboa_2026',
        company: 'Centauro',
        brand: 'Fiat',
        model: '500',
        licensePlate: 'PT-42-TR',
        fuelPolicy: 'Lleno/Lleno',
        insurance: 'Cobertura premium',
        deductible: { amount: 0, currency: 'EUR', conversionRate: 1 },
        includedMileage: 'Ilimitado',
        deposit: { amount: 150, currency: 'EUR', conversionRate: 1 },
        mainDriver: 'Francisco',
        price: { amount: 188, currency: 'EUR', conversionRate: 1 },
        pickupPoint: 'Aeropuerto de Lisboa',
        dropoffPoint: 'Aeropuerto de Lisboa',
        pickupAt: '2026-05-01T12:00',
        dropoffAt: '2026-05-05T18:00',
        pickupLatitude: 38.7742,
        pickupLongitude: -9.1342,
        dropoffLatitude: 38.7742,
        dropoffLongitude: -9.1342,
        conditionPhotoUrls: ['https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=900&q=80'],
        notes: 'Fotos hechas al recoger y devolver.',
      },
    ],
    accommodations: [],
    itineraryDays: [
      { id: 'day_lisboa_1', tripId: 'trip_lisboa_2026', date: '2026-05-02', title: 'Alfama y Baixa', notes: 'Dia a pie.' },
    ],
    itineraryItems: [
      {
        id: 'item_alfama',
        tripId: 'trip_lisboa_2026',
        dayId: 'day_lisboa_1',
        title: 'Alfama',
        description: 'Miradores, tranvia y cena con fado.',
        imageUrl: 'https://images.unsplash.com/photo-1525207934214-58e69a8f8a3a?auto=format&fit=crop&w=900&q=80',
        cost: { amount: 25, currency: 'EUR', conversionRate: 1 },
        latitude: 38.7122,
        longitude: -9.1296,
        recommendations: {
          food: 'Reservar en tasca pequena, no improvisar tarde.',
          transport: 'Moverse a pie y usar tranvia solo fuera de hora punta.',
        },
        visited: true,
        order: 1,
      },
    ],
    activities: [],
    restaurants: [],
    contacts: [],
    insurances: [],
    documents: [],
    journalEntries: [
      {
        id: 'journal_lisboa_1',
        tripId: 'trip_lisboa_2026',
        date: '2026-05-02',
        title: 'Luz de Alfama',
        body: 'La mejor parte fue caminar sin prisa desde Santa Luzia hasta el rio.',
        photoUrls: ['https://images.unsplash.com/photo-1513735492246-483525079686?auto=format&fit=crop&w=900&q=80'],
        mood: 'Tranquilo',
      },
    ],
    expenses: [
      {
        id: 'expense_pasteis',
        tripId: 'trip_lisboa_2026',
        category: 'Comida',
        description: 'Pasteles de nata y cafe',
        date: '2026-05-02',
        cost: { amount: 12, currency: 'EUR', conversionRate: 1 },
        paid: true,
      },
    ],
  },
]
